# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[wallpaper]
backend = "hyprpaper"
custom_paths = ["/home/shakir/.local/share/hyde-wallpapers"]


[battery.notify.threshold]
full = 0
unplug = 0
critical = 0
interval = 0
timer = 0
dock = true
low = 20

"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[cava.hyprlock]
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
max_instances = 1
range = 7
standby = "ğŸ¶"
width = 20

[cava.stdout]
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
max_instances = 1
range = 7
standby = "ğŸ¶"
width = 20

[cava.waybar]
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
max_instances = 1
range = 7
standby = "ğŸ¶"
width = 20

[hyprland_start]
notifications = "mako"
